storage: ./tmp/storage
store:
  s3:
    bucket: xdissentverdaccios3test
auth:
  htpasswd:
    file: ./tmp/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
