// flow-typed signature: 1fba76be83aa8806d59ef99718022ba3
// flow-typed version: <<STUB>>/verdaccio_v^3.0.0-beta.6/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'verdaccio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'verdaccio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'verdaccio/build/api/debug/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/dist-tags' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/package' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/ping' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/publish' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/search' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/user' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/whoami' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/middleware' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/api' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/endpoint/package' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/endpoint/search' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/endpoint/user' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/middleware' {
  declare module.exports: any;
}

declare module 'verdaccio/build/config/env' {
  declare module.exports: any;
}

declare module 'verdaccio/build/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/auth' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/bootstrap' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/cli' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/config-path' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/config' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/local-storage' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/logger' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/notify' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/plugin-loader' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/search' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/status-cats' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/storage-utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/storage' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/up-storage' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/utils/string' {
  declare module.exports: any;
}

declare module 'verdaccio/build/utils/user' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/async_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/axios_v0.17.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/body-parser_v1.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/bunyan_v1.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/chalk_v2.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/commander_v2.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/compression_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/cookies_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/cors_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/express_v4.16.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/http-errors_v1.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/js-yaml_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/JSONStream_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/jsonwebtoken_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/lockfile_v1.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/lunr_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/marked_v0.3.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/mime_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/minimatch_v3.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/mkdirp_v0.5.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/node-mocks-http_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/normalize.css_v7.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/pkginfo_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/react-router-dom_v4.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/request_vx.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/rimraf_v2.x.x' {
  declare module.exports: any;
}

declare module 'verdaccio/flow-typed/npm/semver_v5.1.x' {
  declare module.exports: any;
}

declare module 'verdaccio/jest.config' {
  declare module.exports: any;
}

declare module 'verdaccio/jest.e2e.config' {
  declare module.exports: any;
}

declare module 'verdaccio/jestEnvironment' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/debug/index' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/api/dist-tags' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/api/package' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/api/ping' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/api/publish' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/api/search' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/api/user' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/api/whoami' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/endpoint/index' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/index' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/middleware' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/web/api' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/web/endpoint/package' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/web/endpoint/search' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/web/endpoint/user' {
  declare module.exports: any;
}

declare module 'verdaccio/src/api/web/index' {
  declare module.exports: any;
}

declare module 'verdaccio/src/config/env' {
  declare module.exports: any;
}

declare module 'verdaccio/src/index' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/auth' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/bootstrap' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/cli' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/config-path' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/config' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/local-storage' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/logger' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/notify' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/plugin-loader' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/search' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/status-cats' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/storage-utils' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/storage' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/up-storage' {
  declare module.exports: any;
}

declare module 'verdaccio/src/lib/utils' {
  declare module.exports: any;
}

declare module 'verdaccio/src/utils/string' {
  declare module.exports: any;
}

declare module 'verdaccio/src/utils/user' {
  declare module.exports: any;
}

declare module 'verdaccio/static/main.59c7405d38bec12a8aac' {
  declare module.exports: any;
}

declare module 'verdaccio/test/e2e/e2e.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/e2e/partials/pkg-protected' {
  declare module.exports: any;
}

declare module 'verdaccio/test/e2e/partials/pkg-scoped' {
  declare module.exports: any;
}

declare module 'verdaccio/test/e2e/pre-setup' {
  declare module.exports: any;
}

declare module 'verdaccio/test/e2e/puppeteer_environment' {
  declare module.exports: any;
}

declare module 'verdaccio/test/e2e/setup' {
  declare module.exports: any;
}

declare module 'verdaccio/test/e2e/teardown' {
  declare module.exports: any;
}

declare module 'verdaccio/test/flow/types' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/adduser/adduser' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/adduser/logout' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/basic/basic.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/basic/ping' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/basic/whoIam' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/fixtures/package' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/fixtures/plugins/middlewares' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/gh29' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/index.func' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/lib/simple_server' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/lib/test.utils' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/notifications/notify' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/package/access.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/package/gzip.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/package/scoped.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/performance/race' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/plugins/auth.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/plugins/middleware.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/readme/readme.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/sanity/incomplete' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/sanity/mirror' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/sanity/nullstorage' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/sanity/racycrash' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/sanity/security' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/tags/addtag.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/tags/preserve_tags.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/tags/tags.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/uplink.auth.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/functional/uplink.cache.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/helper/register' {
  declare module.exports: any;
}

declare module 'verdaccio/test/src/request' {
  declare module.exports: any;
}

declare module 'verdaccio/test/src/server_process' {
  declare module.exports: any;
}

declare module 'verdaccio/test/src/server' {
  declare module.exports: any;
}

declare module 'verdaccio/test/src/verdaccio-server' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/api.pkg.access.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/api.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/auth.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/basic_system.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/cli.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/config.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/functionalLibs/request.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/listen_addr.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/local-storage.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/no_proxy.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/parse_interval.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/config/access' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/config/index' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/config/plugin' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/forbidden-place' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/plugin/authenticate' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/publish-api' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/test-plugin-storage/invalid-plugin-sanity/index' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/test-plugin-storage/invalid-plugin/index' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-es6-plugin/dummy' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-es6-plugin/index' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-plugin/index' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/plugin_loader.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/search.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/st_merge.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/store.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/tag_version.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/up-storage.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/utils.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/unit/validate_all.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/__mocks__/api' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/header.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/help.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/noitems.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/notfound.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/package.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/packagedetail.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/packagelist.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/PackageSidebar/dependencies.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/PackageSidebar/lastsync.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/PackageSidebar/maintainerInfo.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/PackageSidebar/maintainers.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/PackageSidebar/module.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/PackageSidebar/moduleContentPlaceholder.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/PackageSidebar/packageSidebar.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/readme.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/search.spec' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/store/login' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/store/logo' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/components/store/packageMeta' {
  declare module.exports: any;
}

declare module 'verdaccio/test/webui/global' {
  declare module.exports: any;
}

declare module 'verdaccio/types/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'verdaccio/build/api/debug/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/debug/index'>;
}
declare module 'verdaccio/build/api/endpoint/api/dist-tags.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/dist-tags'>;
}
declare module 'verdaccio/build/api/endpoint/api/package.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/package'>;
}
declare module 'verdaccio/build/api/endpoint/api/ping.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/ping'>;
}
declare module 'verdaccio/build/api/endpoint/api/publish.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/publish'>;
}
declare module 'verdaccio/build/api/endpoint/api/search.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/search'>;
}
declare module 'verdaccio/build/api/endpoint/api/user.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/user'>;
}
declare module 'verdaccio/build/api/endpoint/api/whoami.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/whoami'>;
}
declare module 'verdaccio/build/api/endpoint/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/index'>;
}
declare module 'verdaccio/build/api/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/index'>;
}
declare module 'verdaccio/build/api/middleware.js' {
  declare module.exports: $Exports<'verdaccio/build/api/middleware'>;
}
declare module 'verdaccio/build/api/web/api.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/api'>;
}
declare module 'verdaccio/build/api/web/endpoint/package.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/endpoint/package'>;
}
declare module 'verdaccio/build/api/web/endpoint/search.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/endpoint/search'>;
}
declare module 'verdaccio/build/api/web/endpoint/user.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/endpoint/user'>;
}
declare module 'verdaccio/build/api/web/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/index'>;
}
declare module 'verdaccio/build/api/web/middleware.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/middleware'>;
}
declare module 'verdaccio/build/config/env.js' {
  declare module.exports: $Exports<'verdaccio/build/config/env'>;
}
declare module 'verdaccio/build/index.js' {
  declare module.exports: $Exports<'verdaccio/build/index'>;
}
declare module 'verdaccio/build/lib/auth.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/auth'>;
}
declare module 'verdaccio/build/lib/bootstrap.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/bootstrap'>;
}
declare module 'verdaccio/build/lib/cli.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/cli'>;
}
declare module 'verdaccio/build/lib/config-path.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/config-path'>;
}
declare module 'verdaccio/build/lib/config.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/config'>;
}
declare module 'verdaccio/build/lib/local-storage.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/local-storage'>;
}
declare module 'verdaccio/build/lib/logger.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/logger'>;
}
declare module 'verdaccio/build/lib/notify.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/notify'>;
}
declare module 'verdaccio/build/lib/plugin-loader.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/plugin-loader'>;
}
declare module 'verdaccio/build/lib/search.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/search'>;
}
declare module 'verdaccio/build/lib/status-cats.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/status-cats'>;
}
declare module 'verdaccio/build/lib/storage-utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/storage-utils'>;
}
declare module 'verdaccio/build/lib/storage.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/storage'>;
}
declare module 'verdaccio/build/lib/up-storage.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/up-storage'>;
}
declare module 'verdaccio/build/lib/utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/utils'>;
}
declare module 'verdaccio/build/utils/string.js' {
  declare module.exports: $Exports<'verdaccio/build/utils/string'>;
}
declare module 'verdaccio/build/utils/user.js' {
  declare module.exports: $Exports<'verdaccio/build/utils/user'>;
}
declare module 'verdaccio/flow-typed/npm/async_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/async_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/axios_v0.17.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/axios_v0.17.x'>;
}
declare module 'verdaccio/flow-typed/npm/body-parser_v1.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/body-parser_v1.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/bunyan_v1.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/bunyan_v1.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/chalk_v2.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/chalk_v2.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/commander_v2.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/commander_v2.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/compression_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/compression_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/cookies_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/cookies_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/cors_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/cors_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/express_v4.16.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/express_v4.16.x'>;
}
declare module 'verdaccio/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/http-errors_v1.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/http-errors_v1.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/jest_v22.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/js-yaml_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/js-yaml_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/JSONStream_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/JSONStream_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/jsonwebtoken_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/jsonwebtoken_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/lockfile_v1.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/lockfile_v1.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/lunr_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/lunr_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/marked_v0.3.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/marked_v0.3.x'>;
}
declare module 'verdaccio/flow-typed/npm/mime_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/mime_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/minimatch_v3.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/minimatch_v3.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/mkdirp_v0.5.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/mkdirp_v0.5.x'>;
}
declare module 'verdaccio/flow-typed/npm/node-mocks-http_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/node-mocks-http_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/normalize.css_v7.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/normalize.css_v7.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/pkginfo_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/pkginfo_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/react-router-dom_v4.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/react-router-dom_v4.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/request_vx.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/request_vx.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/rimraf_v2.x.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/rimraf_v2.x.x'>;
}
declare module 'verdaccio/flow-typed/npm/semver_v5.1.x.js' {
  declare module.exports: $Exports<'verdaccio/flow-typed/npm/semver_v5.1.x'>;
}
declare module 'verdaccio/index' {
  declare module.exports: $Exports<'verdaccio'>;
}
declare module 'verdaccio/index.js' {
  declare module.exports: $Exports<'verdaccio'>;
}
declare module 'verdaccio/jest.config.js' {
  declare module.exports: $Exports<'verdaccio/jest.config'>;
}
declare module 'verdaccio/jest.e2e.config.js' {
  declare module.exports: $Exports<'verdaccio/jest.e2e.config'>;
}
declare module 'verdaccio/jestEnvironment.js' {
  declare module.exports: $Exports<'verdaccio/jestEnvironment'>;
}
declare module 'verdaccio/src/api/debug/index.js' {
  declare module.exports: $Exports<'verdaccio/src/api/debug/index'>;
}
declare module 'verdaccio/src/api/endpoint/api/dist-tags.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/api/dist-tags'>;
}
declare module 'verdaccio/src/api/endpoint/api/package.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/api/package'>;
}
declare module 'verdaccio/src/api/endpoint/api/ping.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/api/ping'>;
}
declare module 'verdaccio/src/api/endpoint/api/publish.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/api/publish'>;
}
declare module 'verdaccio/src/api/endpoint/api/search.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/api/search'>;
}
declare module 'verdaccio/src/api/endpoint/api/user.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/api/user'>;
}
declare module 'verdaccio/src/api/endpoint/api/whoami.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/api/whoami'>;
}
declare module 'verdaccio/src/api/endpoint/index.js' {
  declare module.exports: $Exports<'verdaccio/src/api/endpoint/index'>;
}
declare module 'verdaccio/src/api/index.js' {
  declare module.exports: $Exports<'verdaccio/src/api/index'>;
}
declare module 'verdaccio/src/api/middleware.js' {
  declare module.exports: $Exports<'verdaccio/src/api/middleware'>;
}
declare module 'verdaccio/src/api/web/api.js' {
  declare module.exports: $Exports<'verdaccio/src/api/web/api'>;
}
declare module 'verdaccio/src/api/web/endpoint/package.js' {
  declare module.exports: $Exports<'verdaccio/src/api/web/endpoint/package'>;
}
declare module 'verdaccio/src/api/web/endpoint/search.js' {
  declare module.exports: $Exports<'verdaccio/src/api/web/endpoint/search'>;
}
declare module 'verdaccio/src/api/web/endpoint/user.js' {
  declare module.exports: $Exports<'verdaccio/src/api/web/endpoint/user'>;
}
declare module 'verdaccio/src/api/web/index.js' {
  declare module.exports: $Exports<'verdaccio/src/api/web/index'>;
}
declare module 'verdaccio/src/config/env.js' {
  declare module.exports: $Exports<'verdaccio/src/config/env'>;
}
declare module 'verdaccio/src/index.js' {
  declare module.exports: $Exports<'verdaccio/src/index'>;
}
declare module 'verdaccio/src/lib/auth.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/auth'>;
}
declare module 'verdaccio/src/lib/bootstrap.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/bootstrap'>;
}
declare module 'verdaccio/src/lib/cli.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/cli'>;
}
declare module 'verdaccio/src/lib/config-path.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/config-path'>;
}
declare module 'verdaccio/src/lib/config.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/config'>;
}
declare module 'verdaccio/src/lib/local-storage.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/local-storage'>;
}
declare module 'verdaccio/src/lib/logger.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/logger'>;
}
declare module 'verdaccio/src/lib/notify.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/notify'>;
}
declare module 'verdaccio/src/lib/plugin-loader.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/plugin-loader'>;
}
declare module 'verdaccio/src/lib/search.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/search'>;
}
declare module 'verdaccio/src/lib/status-cats.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/status-cats'>;
}
declare module 'verdaccio/src/lib/storage-utils.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/storage-utils'>;
}
declare module 'verdaccio/src/lib/storage.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/storage'>;
}
declare module 'verdaccio/src/lib/up-storage.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/up-storage'>;
}
declare module 'verdaccio/src/lib/utils.js' {
  declare module.exports: $Exports<'verdaccio/src/lib/utils'>;
}
declare module 'verdaccio/src/utils/string.js' {
  declare module.exports: $Exports<'verdaccio/src/utils/string'>;
}
declare module 'verdaccio/src/utils/user.js' {
  declare module.exports: $Exports<'verdaccio/src/utils/user'>;
}
declare module 'verdaccio/static/main.59c7405d38bec12a8aac.js' {
  declare module.exports: $Exports<'verdaccio/static/main.59c7405d38bec12a8aac'>;
}
declare module 'verdaccio/test/e2e/e2e.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/e2e/e2e.spec'>;
}
declare module 'verdaccio/test/e2e/partials/pkg-protected.js' {
  declare module.exports: $Exports<'verdaccio/test/e2e/partials/pkg-protected'>;
}
declare module 'verdaccio/test/e2e/partials/pkg-scoped.js' {
  declare module.exports: $Exports<'verdaccio/test/e2e/partials/pkg-scoped'>;
}
declare module 'verdaccio/test/e2e/pre-setup.js' {
  declare module.exports: $Exports<'verdaccio/test/e2e/pre-setup'>;
}
declare module 'verdaccio/test/e2e/puppeteer_environment.js' {
  declare module.exports: $Exports<'verdaccio/test/e2e/puppeteer_environment'>;
}
declare module 'verdaccio/test/e2e/setup.js' {
  declare module.exports: $Exports<'verdaccio/test/e2e/setup'>;
}
declare module 'verdaccio/test/e2e/teardown.js' {
  declare module.exports: $Exports<'verdaccio/test/e2e/teardown'>;
}
declare module 'verdaccio/test/flow/types.js' {
  declare module.exports: $Exports<'verdaccio/test/flow/types'>;
}
declare module 'verdaccio/test/functional/adduser/adduser.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/adduser/adduser'>;
}
declare module 'verdaccio/test/functional/adduser/logout.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/adduser/logout'>;
}
declare module 'verdaccio/test/functional/basic/basic.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/basic/basic.spec'>;
}
declare module 'verdaccio/test/functional/basic/ping.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/basic/ping'>;
}
declare module 'verdaccio/test/functional/basic/whoIam.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/basic/whoIam'>;
}
declare module 'verdaccio/test/functional/fixtures/package.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/fixtures/package'>;
}
declare module 'verdaccio/test/functional/fixtures/plugins/middlewares.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/fixtures/plugins/middlewares'>;
}
declare module 'verdaccio/test/functional/gh29.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/gh29'>;
}
declare module 'verdaccio/test/functional/index.func.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/index.func'>;
}
declare module 'verdaccio/test/functional/lib/simple_server.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/lib/simple_server'>;
}
declare module 'verdaccio/test/functional/lib/test.utils.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/lib/test.utils'>;
}
declare module 'verdaccio/test/functional/notifications/notify.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/notifications/notify'>;
}
declare module 'verdaccio/test/functional/package/access.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/package/access.spec'>;
}
declare module 'verdaccio/test/functional/package/gzip.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/package/gzip.spec'>;
}
declare module 'verdaccio/test/functional/package/scoped.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/package/scoped.spec'>;
}
declare module 'verdaccio/test/functional/performance/race.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/performance/race'>;
}
declare module 'verdaccio/test/functional/plugins/auth.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/plugins/auth.spec'>;
}
declare module 'verdaccio/test/functional/plugins/middleware.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/plugins/middleware.spec'>;
}
declare module 'verdaccio/test/functional/readme/readme.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/readme/readme.spec'>;
}
declare module 'verdaccio/test/functional/sanity/incomplete.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/sanity/incomplete'>;
}
declare module 'verdaccio/test/functional/sanity/mirror.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/sanity/mirror'>;
}
declare module 'verdaccio/test/functional/sanity/nullstorage.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/sanity/nullstorage'>;
}
declare module 'verdaccio/test/functional/sanity/racycrash.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/sanity/racycrash'>;
}
declare module 'verdaccio/test/functional/sanity/security.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/sanity/security'>;
}
declare module 'verdaccio/test/functional/tags/addtag.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/tags/addtag.spec'>;
}
declare module 'verdaccio/test/functional/tags/preserve_tags.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/tags/preserve_tags.spec'>;
}
declare module 'verdaccio/test/functional/tags/tags.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/tags/tags.spec'>;
}
declare module 'verdaccio/test/functional/uplink.auth.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/uplink.auth.spec'>;
}
declare module 'verdaccio/test/functional/uplink.cache.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/functional/uplink.cache.spec'>;
}
declare module 'verdaccio/test/helper/register.js' {
  declare module.exports: $Exports<'verdaccio/test/helper/register'>;
}
declare module 'verdaccio/test/src/request.js' {
  declare module.exports: $Exports<'verdaccio/test/src/request'>;
}
declare module 'verdaccio/test/src/server_process.js' {
  declare module.exports: $Exports<'verdaccio/test/src/server_process'>;
}
declare module 'verdaccio/test/src/server.js' {
  declare module.exports: $Exports<'verdaccio/test/src/server'>;
}
declare module 'verdaccio/test/src/verdaccio-server.js' {
  declare module.exports: $Exports<'verdaccio/test/src/verdaccio-server'>;
}
declare module 'verdaccio/test/unit/api.pkg.access.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/api.pkg.access.spec'>;
}
declare module 'verdaccio/test/unit/api.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/api.spec'>;
}
declare module 'verdaccio/test/unit/auth.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/auth.spec'>;
}
declare module 'verdaccio/test/unit/basic_system.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/basic_system.spec'>;
}
declare module 'verdaccio/test/unit/cli.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/cli.spec'>;
}
declare module 'verdaccio/test/unit/config.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/config.spec'>;
}
declare module 'verdaccio/test/unit/functionalLibs/request.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/functionalLibs/request.spec'>;
}
declare module 'verdaccio/test/unit/listen_addr.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/listen_addr.spec'>;
}
declare module 'verdaccio/test/unit/local-storage.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/local-storage.spec'>;
}
declare module 'verdaccio/test/unit/no_proxy.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/no_proxy.spec'>;
}
declare module 'verdaccio/test/unit/parse_interval.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/parse_interval.spec'>;
}
declare module 'verdaccio/test/unit/partials/config/access.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/config/access'>;
}
declare module 'verdaccio/test/unit/partials/config/index.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/config/index'>;
}
declare module 'verdaccio/test/unit/partials/config/plugin.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/config/plugin'>;
}
declare module 'verdaccio/test/unit/partials/forbidden-place.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/forbidden-place'>;
}
declare module 'verdaccio/test/unit/partials/plugin/authenticate.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/plugin/authenticate'>;
}
declare module 'verdaccio/test/unit/partials/publish-api.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/publish-api'>;
}
declare module 'verdaccio/test/unit/partials/test-plugin-storage/invalid-plugin-sanity/index.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/test-plugin-storage/invalid-plugin-sanity/index'>;
}
declare module 'verdaccio/test/unit/partials/test-plugin-storage/invalid-plugin/index.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/test-plugin-storage/invalid-plugin/index'>;
}
declare module 'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-es6-plugin/dummy.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-es6-plugin/dummy'>;
}
declare module 'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-es6-plugin/index.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-es6-plugin/index'>;
}
declare module 'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-plugin/index.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/partials/test-plugin-storage/verdaccio-plugin/index'>;
}
declare module 'verdaccio/test/unit/plugin_loader.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/plugin_loader.spec'>;
}
declare module 'verdaccio/test/unit/search.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/search.spec'>;
}
declare module 'verdaccio/test/unit/st_merge.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/st_merge.spec'>;
}
declare module 'verdaccio/test/unit/store.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/store.spec'>;
}
declare module 'verdaccio/test/unit/tag_version.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/tag_version.spec'>;
}
declare module 'verdaccio/test/unit/up-storage.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/up-storage.spec'>;
}
declare module 'verdaccio/test/unit/utils.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/utils.spec'>;
}
declare module 'verdaccio/test/unit/validate_all.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/unit/validate_all.spec'>;
}
declare module 'verdaccio/test/webui/components/__mocks__/api.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/__mocks__/api'>;
}
declare module 'verdaccio/test/webui/components/header.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/header.spec'>;
}
declare module 'verdaccio/test/webui/components/help.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/help.spec'>;
}
declare module 'verdaccio/test/webui/components/noitems.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/noitems.spec'>;
}
declare module 'verdaccio/test/webui/components/notfound.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/notfound.spec'>;
}
declare module 'verdaccio/test/webui/components/package.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/package.spec'>;
}
declare module 'verdaccio/test/webui/components/packagedetail.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/packagedetail.spec'>;
}
declare module 'verdaccio/test/webui/components/packagelist.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/packagelist.spec'>;
}
declare module 'verdaccio/test/webui/components/PackageSidebar/dependencies.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/PackageSidebar/dependencies.spec'>;
}
declare module 'verdaccio/test/webui/components/PackageSidebar/lastsync.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/PackageSidebar/lastsync.spec'>;
}
declare module 'verdaccio/test/webui/components/PackageSidebar/maintainerInfo.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/PackageSidebar/maintainerInfo.spec'>;
}
declare module 'verdaccio/test/webui/components/PackageSidebar/maintainers.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/PackageSidebar/maintainers.spec'>;
}
declare module 'verdaccio/test/webui/components/PackageSidebar/module.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/PackageSidebar/module.spec'>;
}
declare module 'verdaccio/test/webui/components/PackageSidebar/moduleContentPlaceholder.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/PackageSidebar/moduleContentPlaceholder.spec'>;
}
declare module 'verdaccio/test/webui/components/PackageSidebar/packageSidebar.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/PackageSidebar/packageSidebar.spec'>;
}
declare module 'verdaccio/test/webui/components/readme.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/readme.spec'>;
}
declare module 'verdaccio/test/webui/components/search.spec.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/search.spec'>;
}
declare module 'verdaccio/test/webui/components/store/login.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/store/login'>;
}
declare module 'verdaccio/test/webui/components/store/logo.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/store/logo'>;
}
declare module 'verdaccio/test/webui/components/store/packageMeta.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/components/store/packageMeta'>;
}
declare module 'verdaccio/test/webui/global.js' {
  declare module.exports: $Exports<'verdaccio/test/webui/global'>;
}
declare module 'verdaccio/types/index.js' {
  declare module.exports: $Exports<'verdaccio/types/index'>;
}
